/// Flutter icons RCNavigation
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RCNavigation
///      fonts:
///       - asset: fonts/RCNavigation.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RCNavigation {
  RCNavigation._();

  static const _kFontFam = 'RCNavigation';
  static const _kFontPkg = null;

  static const IconData icon_rhythm =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tool =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pitch =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
